# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 15:04
from __future__ import unicode_literals

import banner_rotator.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('alt', models.CharField(blank=True, default='', max_length=255, verbose_name='Image alt')),
                ('url', models.URLField(verbose_name='URL')),
                ('url_target', models.CharField(choices=[('_self', 'Current page'), ('_blank', 'Blank page')], default='', max_length=10, verbose_name='Target')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('max_views', models.IntegerField(default=0, verbose_name='Max views')),
                ('max_clicks', models.IntegerField(default=0, verbose_name='Max clicks')),
                ('weight', models.IntegerField(choices=[[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7], [8, 8], [9, 9], [10, 10]], default=5, help_text='A ten will display 10 times more often that a one.', verbose_name='Weight')),
                ('file', models.FileField(upload_to=banner_rotator.models.get_banner_upload_to, verbose_name='File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Start at')),
                ('finish_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Finish at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Clicked at')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('referrer', models.URLField(blank=True, null=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='banner_rotator.Banner')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_clicks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('width', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Width')),
                ('height', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Height')),
            ],
            options={
                'verbose_name': 'place',
                'verbose_name_plural': 'places',
            },
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set([('slug',)]),
        ),
        migrations.AddField(
            model_name='banner',
            name='campaign',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='banner_rotator.Campaign', verbose_name='Campaign'),
        ),
        migrations.AddField(
            model_name='banner',
            name='places',
            field=models.ManyToManyField(db_index=True, related_name='banners', to='banner_rotator.Place', verbose_name='Place'),
        ),
    ]
